export const harmonicRhythmPresets = {
            pillar: { type: 'bar_local', offsets: [0] },
            pulse: { type: 'bar_local', offsets: [0, 2] },
            march: { type: 'bar_local', offsets: [0, 1, 2, 3] },
            waltz_feel: { type: 'bar_local', offsets: [0, 1, 2] },
            push: { type: 'bar_local', offsets: [3.5] },
            charleston: { type: 'bar_local', offsets: [0, 1.5] },
            backbeat: { type: 'bar_local', offsets: [1, 3] },
            anticipator: { type: 'bar_local', offsets: [1.5, 3.5] },
            heartbeat: { type: 'bar_local', offsets: [0, 0.5] },
            off_grid: { type: 'bar_local', offsets: [0.5, 1.5, 2.5, 3.5] },
            gallop: { type: 'bar_local', offsets: [0, 0.75, 1] },
            hemiola: { type: 'bar_local', offsets: [0, 1.5, 3] },
            slow_cycle: { type: 'bar_spanning', pattern: 'slow_cycle', barOffsets: {0: [0], 1: [3], 2: [2], 3: [1]} },
            tremolo_block: { type: 'bar_local', offsets: [0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.25, 2.5, 2.75, 3, 3.25, 3.5, 3.75] },
            ghost_notes: { type: 'bar_local', offsets: [0, 2.5, 3.5] },
            bossa_nova: { type: 'bar_spanning', pattern: 'bossa_nova', spanBars: 2, offsets: [0, 1.5, 3, 4.5] },
            cinematic_swell: { type: 'bar_local', offsets: [1] },
            trap_triplets: { type: 'bar_local', offsets: [2, 2.33, 2.66] },
            pyramid: { type: 'bar_spanning', pattern: 'pyramid', barOffsets: {0: [0], 1: [0, 2], 2: [0, 1, 2, 3], 3: [0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.25, 2.5, 2.75, 3, 3.25, 3.5, 3.75]} },
            random_walk: { type: 'algorithmic', pattern: 'random_walk', gridSize: 0.25 },
            triplet_eighths: { type: 'bar_local', offsets: [0, 0.33, 0.66, 1, 1.33, 1.66, 2, 2.33, 2.66, 3, 3.33, 3.66] },
            triplet_quarters: { type: 'bar_local', offsets: [0, 0.66, 1.33, 2, 2.66, 3.33] },
            e_and_a: { type: 'bar_local', offsets: [0.25, 1.25, 2.25, 3.25] },
            double_pushed: { type: 'bar_local', offsets: [1.5, 3.5] },
            five_over_four: { type: 'algorithmic', pattern: 'five_over_four', interval: 0.8 },
            pedal: { type: 'algorithmic', pattern: 'pedal' },
            decrescendo: { type: 'algorithmic', pattern: 'decrescendo' },
            accelerando: { type: 'algorithmic', pattern: 'accelerando' }
        };
